sudo: false

addons:
  apt:
    packages:
      - oracle-java8-installer
builds:
language: java
jdk:
  - oraclejdk8

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

script: sh -c 'mvn clean test -f Application/frogger/pom.xml'
